### ISSUE TITLE
Changes on api-key persistence generate problem on v0.20.1

### ISSUE THREAD

**Issue by xcloudscript** [MagaluCloud/terraform-provider-mgc#22]
Hi, guys!

The most recent version 0.20.1 broken the bucket creation.

│ Error: Unable to create mgc_object_storage_buckets
│ 
│   with mgc_object_storage_buckets.bucket,
│   on main.tf line 10, in resource "mgc_object_storage_buckets" "bucket":
│   10: resource "mgc_object_storage_buckets" "bucket" {
│ 
│ Service returned with error: api-key not set, see how to set it with "mgc
│ object-storage api-key -h"

**Comment by xcloudscript** [comment]
Version 0.19.3 works fine.

**Comment by publi0** [comment]
I understand you're having trouble. Our recent update to standardize parameter names might be the cause. Please try replacing the old api-key parameter with key-pair in your configuration.

You can find more information in the updated documentation: https://registry.terraform.io/providers/MagaluCloud/mgc/0.20.0/docs#nested-schema-for-object_storage

We apologize for any inconvenience caused by this change. We're continually improving our project and standardizing names to make it easier to use in the long run. The old api-key was sometimes confused with the authentication key, so we've made this adjustment for clarity.

**Comment by publi0** [comment]
If this doesn't resolve your issue or you have any other questions, please feel free to open a new issue. ;)
